### ISSUE TITLE
Nested elements not correctly parsed

### ISSUE THREAD

**Issue by scruffian** [grommet/jsx-to-string#39]
I am having an issue with nested elements. This:

```jsxToString(<span>one <span>two <span>three</span></span></span>)```

outputs:

```
<span>
  <span>
    <span>
      three
    </span>
  </span>
</span>
```

Is this expected?

**Comment by alansouzati** [comment]
Yeah this looks like a bug.

I believe it has to do with the fact the "one" is a text and is getting stripped out for some reason.

Here is a codepen with a workaround.

https://codesandbox.io/s/o90r4rz9p6

I will try to get a fix for this soon.

**Comment by alansouzati** [comment]
Fixed. 1.4.0 released

https://github.com/grommet/jsx-to-string/releases/tag/v1.4.0

**Comment by GuruM** [comment]
@alansouzati I believe this is still an issue in v.1.4.0: 
https://codesandbox.io/s/918qyr149w

**Comment by GuruM** [comment]
It looks like your commit works, but it wasn't included in v1.4.0 somehow 🤔
